#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_APP_LOG_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_CONNECTION_PRESENT
#define SL_CATALOG_BLUETOOTH_PRESENT
#define SL_CATALOG_BTMESH_CTL_SERVER_PRESENT
#define SL_CATALOG_BTMESH_DCD_CONFIGURATION_PRESENT
#define SL_CATALOG_BTMESH_FEATURE_FRIEND_PRESENT
#define SL_CATALOG_BTMESH_FEATURE_PROXY_PRESENT
#define SL_CATALOG_BTMESH_LIGHTING_SERVER_PRESENT
#define SL_CATALOG_BTMESH_SCENE_SERVER_PRESENT
#define SL_CATALOG_BTMESH_PRESENT
#define SL_CATALOG_CLI_PRESENT
#define SL_CATALOG_DEVICE_INIT_NVIC_PRESENT
#define SL_CATALOG_GATT_CONFIGURATION_PRESENT
#define SL_CATALOG_IOSTREAM_UART_COMMON_PRESENT
#define SL_CATALOG_IOSTREAM_USART_PRESENT
#define SL_CATALOG_POWER_MANAGER_PRESENT
#define SL_CATALOG_RAIL_UTIL_RF_PATH_PRESENT
#define SL_CATALOG_SIMPLE_TIMER_PRESENT

#endif // SL_COMPONENT_CATALOG_H
